<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Favoris Chrome</title>
    <link rel="stylesheet" href="styles/main.css">
</head>
<body>
    <div id="app">
        <h1>Mes Favoris Chrome</h1>
        <div id="categories">
            <!-- Catégories ici -->
        </div>
        <div id="links">
            <!-- Liens ici -->
        </div>
    </div>
    <script src="scripts/main.js"></script>
</body>
</html>
